version: '3.8'

services:
  app:
    build: .
    ports:
      - "5002:5002"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=5002
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    command: npm run dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
